# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "dosayles"
description: > # this means to ignore newlines until "email:"
    Doug's personal web page and blog(ish) pertaining to big data

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/link-building.png"
float_logo: true # true, false (default)
btn: "/assets/images/menu_btn.png"

# blog cover
#cover: "/assets/images/intro-bg.jpg"
cover: "/assets/images/bd_splash.jpg"
footer: "/assets/images/bd_footer5.jpg"

name: 'Douglas Sayles'
author: 'Douglas Sayles'
author_image: "/assets/images/dosayles.jpg"

paginate:	5

url: "https://dosayles.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dosayles'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dosayles
    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

  - icon:	linkedin
    url:	https://linkedin.com/in/dosayles
    desc: Connect with me on linked in
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dosayles
    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
