# Jekyll Defaults
title: dosayles
description: Doug's personal web page and blog(ish)
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://dosayles.github.io"
highlighter: rouge
markdown: kramdown
permalink: /:title
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
